using PSMPE.Portal.Domain.Enums;

namespace PSMPE.Portal.Application.Members.Dtos;

public record MemberDto(
    Guid Id,
    Guid UserId,
    string Email,
    string FirstName,
    string? MiddleName,
    string LastName,
    string? Suffix,
    DateOnly? Birthdate,
    string? Gender,
    string? CivilStatus,
    string? EducationLevel,
    string? SchoolName,
    string? CourseYearGraduated,
    string? SpecifiedProfession,
    string? MobileNumber,
    string? HouseNo,
    string? Street,
    string? Barangay,
    string? CityMunicipality,
    string? Province,
    string? ZipCode,
    string? MailingHouseNo,
    string? MailingStreet,
    string? MailingBarangay,
    string? MailingCityMunicipality,
    string? MailingProvince,
    string? MailingZipCode,
    string? HousePhone,
    string? Website,
    string? FacebookUrl,
    string? LinkedInUrl,
    string? XUrl,
    string? InstagramUrl,
    string? MembershipNo,
    string? PrcLicenseNo,
    DateOnly? PrcRegistrationDate,
    DateOnly? PrcValidUntilDate,
    string? PtrNumber,
    string? Tin,
    bool PrcIdVerified,
    string? PendingPrcLicenseNo,
    DateOnly? PendingPrcRegistrationDate,
    DateOnly? PendingPrcValidUntilDate,
    string? PrcVerificationRejectedReason,
    string Chapter,
    string? EmploymentStatus,
    string? Company,
    string? Position,
    string? BusinessAddress,
    int? YearsOfPractice,
    string? Specialization,
    string? Skills,
    string MemberType,
    MembershipStatus Status,
    DateOnly? RenewalDueDate,
    string? NationalDuesReferenceNo,
    DateTimeOffset? ApprovedAt,
    DateTimeOffset? SubmittedAt,
    bool IsInGracePeriod,
    DateTimeOffset CreatedAt,
    DateTimeOffset? UpdatedAt);

/// <summary>
/// Admin-only: creates a Member profile for an existing user. MembershipNo is optional - PSMPE
/// assigns its own control number, and an admin creating a profile may not have it yet. It can be
/// supplied later on the edit form, and is mandatory at approval.
/// </summary>
public record CreateMemberRequest(
    Guid UserId,
    string? MembershipNo,
    string FirstName,
    string? MiddleName,
    string LastName,
    string? Suffix,
    DateOnly? Birthdate,
    string? Gender,
    string? CivilStatus,
    string? EducationLevel,
    string? SchoolName,
    string? CourseYearGraduated,
    string? SpecifiedProfession,
    string? MobileNumber,
    string? HouseNo,
    string? Street,
    string? Barangay,
    string? CityMunicipality,
    string? Province,
    string? ZipCode,
    string? MailingHouseNo,
    string? MailingStreet,
    string? MailingBarangay,
    string? MailingCityMunicipality,
    string? MailingProvince,
    string? MailingZipCode,
    string? HousePhone,
    string? Website,
    string? FacebookUrl,
    string? LinkedInUrl,
    string? XUrl,
    string? InstagramUrl,
    string? PrcLicenseNo,
    DateOnly? PrcRegistrationDate,
    DateOnly? PrcValidUntilDate,
    string? PtrNumber,
    string? Tin,
    string Chapter,
    string? EmploymentStatus,
    string? Company,
    string? Position,
    string? BusinessAddress,
    int? YearsOfPractice,
    string? Specialization,
    string? Skills,
    string MemberType,
    DateOnly? RenewalDueDate,
    string? NationalDuesReferenceNo);

/// <summary>
/// Admin-only: can change Status, unlike UpdateMyProfileRequest - membership status is a business
/// decision, not self-service. No PrcIdVerified field here (removed) - verification is only ever
/// set via MemberService.ApprovePrcVerificationAsync/RejectPrcVerificationAsync, so every decision
/// goes through the audit trail rather than a raw toggle.
/// </summary>
public record UpdateMemberRequest(
    string FirstName,
    string? MiddleName,
    string LastName,
    string? Suffix,
    DateOnly? Birthdate,
    string? Gender,
    string? CivilStatus,
    string? EducationLevel,
    string? SchoolName,
    string? CourseYearGraduated,
    string? SpecifiedProfession,
    string? MobileNumber,
    string? HouseNo,
    string? Street,
    string? Barangay,
    string? CityMunicipality,
    string? Province,
    string? ZipCode,
    string? MailingHouseNo,
    string? MailingStreet,
    string? MailingBarangay,
    string? MailingCityMunicipality,
    string? MailingProvince,
    string? MailingZipCode,
    string? HousePhone,
    string? Website,
    string? FacebookUrl,
    string? LinkedInUrl,
    string? XUrl,
    string? InstagramUrl,
    string? PrcLicenseNo,
    DateOnly? PrcRegistrationDate,
    DateOnly? PrcValidUntilDate,
    string? PtrNumber,
    string? Tin,
    string Chapter,
    string? EmploymentStatus,
    string? Company,
    string? Position,
    string? BusinessAddress,
    int? YearsOfPractice,
    string? Specialization,
    string? Skills,
    string MemberType,
    MembershipStatus Status,
    DateOnly? RenewalDueDate,
    string? NationalDuesReferenceNo,
    /// <summary>The correction path for a control number mistyped at approval. Null or blank means
    /// "not supplied" and leaves the stored value alone - it is deliberately NOT a way to clear an
    /// approved member's number, and the default keeps every existing caller compiling.</summary>
    string? MembershipNo = null);

/// <summary>
/// Self-service: no Status or MembershipNo - both are admin/business-controlled, not editable by
/// the member themselves. MemberType/Chapter are only honored while the application is still a
/// draft (SubmittedAt null) - see MemberService.UpsertMyProfileAsync. PrcIdReuploaded asserts "I
/// just uploaded a new RMP/PRC ID in this edit" when PrcLicenseNo, PrcRegistrationDate, or
/// PrcValidUntilDate changes - the server independently verifies this against the actual
/// MemberUpload row rather than trusting the flag alone.
/// </summary>
public record UpdateMyProfileRequest(
    string FirstName,
    string? MiddleName,
    string LastName,
    string? Suffix,
    DateOnly? Birthdate,
    string? Gender,
    string? CivilStatus,
    string? EducationLevel,
    string? SchoolName,
    string? CourseYearGraduated,
    string? SpecifiedProfession,
    string? MobileNumber,
    string? HouseNo,
    string? Street,
    string? Barangay,
    string? CityMunicipality,
    string? Province,
    string? ZipCode,
    string? MailingHouseNo,
    string? MailingStreet,
    string? MailingBarangay,
    string? MailingCityMunicipality,
    string? MailingProvince,
    string? MailingZipCode,
    string? HousePhone,
    string? Website,
    string? FacebookUrl,
    string? LinkedInUrl,
    string? XUrl,
    string? InstagramUrl,
    string? PrcLicenseNo,
    DateOnly? PrcRegistrationDate,
    DateOnly? PrcValidUntilDate,
    string? PtrNumber,
    string? Tin,
    string Chapter,
    string? EmploymentStatus,
    string? Company,
    string? Position,
    string? BusinessAddress,
    int? YearsOfPractice,
    string? Specialization,
    string? Skills,
    string MemberType,
    bool PrcIdReuploaded = false);

public record RejectPrcVerificationRequest(string Reason);

public record PrcVerificationHistoryDto(
    Guid Id,
    string? OldValue,
    string? NewValue,
    string? DocumentStorageKey,
    PrcVerificationDecision Decision,
    string? Reason,
    Guid DecidedByUserId,
    DateTimeOffset CreatedAt);

/// <summary>
/// Admin-only: approving an application requires PSMPE's own membership control number, which the
/// portal never generates. Free text (trimmed, max 32 chars) so the society's numbering scheme
/// isn't second-guessed, but it must not already belong to another member.
/// </summary>
public record ApproveMemberRequest(string MembershipNo);
